export interface TeamDetail {
  id: number;
  name: string;
  shortName: string;
  logo: string;
  country: string;
  isNational: boolean;
  founded: number;
  stadium: string;
  stadiumCity: string;
  stadiumCapacity: number;
  manager: string;
  league?: string;
  leagueLogo?: string;
  primaryColor: string;
  secondaryColor: string;
  description: string;
  trophies: { name: string; count: number }[];
  keyPlayers: { name: string; position: string; nationality: string; image: string }[];
  recentNews: { title: string; tag: string; date: string }[];
  stats: { label: string; value: string }[];
  website?: string;
}

export const TEAM_DETAILS: Record<number, TeamDetail> = {
  // ── CLUBS ──────────────────────────────────────────────────────────────────

  50: {
    id: 50,
    name: "Manchester City",
    shortName: "Man City",
    logo: "https://media.api-sports.io/football/teams/50.png",
    country: "England",
    isNational: false,
    founded: 1880,
    stadium: "Etihad Stadium",
    stadiumCity: "Manchester",
    stadiumCapacity: 53400,
    manager: "Pep Guardiola",
    league: "Premier League",
    leagueLogo: "https://media.api-sports.io/football/leagues/39.png",
    primaryColor: "#6CABDD",
    secondaryColor: "#1C2C5B",
    description: "Manchester City F.C. is an English football club based in Manchester. Founded in 1880 as St. Mark's, they play at the Etihad Stadium and are one of the wealthiest and most successful clubs in the world, having won multiple Premier League titles and the UEFA Champions League in 2023.",
    trophies: [
      { name: "Premier League", count: 10 },
      { name: "UEFA Champions League", count: 1 },
      { name: "FA Cup", count: 7 },
      { name: "EFL Cup", count: 8 },
      { name: "Community Shield", count: 7 },
    ],
    keyPlayers: [
      { name: "Erling Haaland", position: "ST", nationality: "Norway", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/7/71/Erling_Haaland_June_2025.jpg/500px-Erling_Haaland_June_2025.jpg" },
      { name: "Kevin De Bruyne", position: "CM", nationality: "Belgium", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/4/40/Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg/500px-Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg" },
      { name: "Phil Foden", position: "AM", nationality: "England", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/5/53/2023-10-04_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League%2C_RB_Leipzig_-_Manchester_City_FC_1DX_2613%2C_Phil_Foden.jpg/500px-2023-10-04_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League%2C_RB_Leipzig_-_Manchester_City_FC_1DX_2613%2C_Phil_Foden.jpg" },
    ],
    recentNews: [
      { title: "Guardiola eyes triple again as City dominate Premier League table", tag: "Premier League", date: "2025-05-20" },
      { title: "Haaland nets hat-trick as Manchester City thrash relegation side", tag: "Match Report", date: "2025-05-16" },
      { title: "City agree summer signing deal for top La Liga midfielder", tag: "Transfer", date: "2025-05-10" },
    ],
    stats: [
      { label: "League Position", value: "1st" },
      { label: "Goals Scored", value: "89" },
      { label: "Clean Sheets", value: "21" },
      { label: "Win Rate", value: "74%" },
    ],
    website: "https://www.mancity.com",
  },

  40: {
    id: 40,
    name: "Liverpool F.C.",
    shortName: "Liverpool",
    logo: "https://media.api-sports.io/football/teams/40.png",
    country: "England",
    isNational: false,
    founded: 1892,
    stadium: "Anfield",
    stadiumCity: "Liverpool",
    stadiumCapacity: 61276,
    manager: "Arne Slot",
    league: "Premier League",
    leagueLogo: "https://media.api-sports.io/football/leagues/39.png",
    primaryColor: "#C8102E",
    secondaryColor: "#00B2A9",
    description: "Liverpool F.C. is one of England's most decorated football clubs, founded in 1892. The club plays at Anfield and is renowned globally for its passionate fanbase and rich history, including 6 UEFA Champions League titles and 20 league championships.",
    trophies: [
      { name: "English Top Flight", count: 19 },
      { name: "UEFA Champions League", count: 6 },
      { name: "FA Cup", count: 8 },
      { name: "EFL Cup", count: 10 },
      { name: "UEFA Cup / Europa League", count: 3 },
    ],
    keyPlayers: [
      { name: "Mohamed Salah", position: "RW", nationality: "Egypt", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Mohamed_Salah_2018.jpg/500px-Mohamed_Salah_2018.jpg" },
      { name: "Virgil van Dijk", position: "CB", nationality: "Netherlands", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/5/5d/20160604_AUT_NED_8876_%28cropped%29.jpg/500px-20160604_AUT_NED_8876_%28cropped%29.jpg" },
      { name: "Trent Alexander-Arnold", position: "RB", nationality: "England", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/5/5d/Trent_Alexander-Arnold_2018_%28cropped%29.jpg" },
    ],
    recentNews: [
      { title: "Arne Slot's Liverpool continue flying start to Premier League season", tag: "Premier League", date: "2025-05-18" },
      { title: "Salah closes in on all-time Liverpool scoring record", tag: "Stats", date: "2025-05-14" },
      { title: "Anfield set for 61,000-seat capacity as expansion nears completion", tag: "Club News", date: "2025-05-08" },
    ],
    stats: [
      { label: "League Position", value: "2nd" },
      { label: "Goals Scored", value: "81" },
      { label: "Clean Sheets", value: "17" },
      { label: "Win Rate", value: "68%" },
    ],
    website: "https://www.liverpoolfc.com",
  },

  42: {
    id: 42,
    name: "Arsenal F.C.",
    shortName: "Arsenal",
    logo: "https://media.api-sports.io/football/teams/42.png",
    country: "England",
    isNational: false,
    founded: 1886,
    stadium: "Emirates Stadium",
    stadiumCity: "London",
    stadiumCapacity: 60704,
    manager: "Mikel Arteta",
    league: "Premier League",
    leagueLogo: "https://media.api-sports.io/football/leagues/39.png",
    primaryColor: "#EF0107",
    secondaryColor: "#063672",
    description: "Arsenal F.C. is a professional football club based in Islington, London. Founded in 1886 as Dial Square, they play at the Emirates Stadium. The Gunners are known for their 'Invincibles' 2003-04 season and have historically been one of England's top clubs.",
    trophies: [
      { name: "English Top Flight", count: 13 },
      { name: "FA Cup", count: 14 },
      { name: "EFL Cup", count: 2 },
      { name: "Community Shield", count: 17 },
      { name: "UEFA Cup Winners' Cup", count: 1 },
    ],
    keyPlayers: [
      { name: "Bukayo Saka", position: "RW", nationality: "England", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/c/cd/1_bukayo_saka_arsenal_2025_%28cropped%29.jpg/500px-1_bukayo_saka_arsenal_2025_%28cropped%29.jpg" },
      { name: "Martin Ødegaard", position: "CAM", nationality: "Norway", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Norway_Italy_-_June_2025_E_04.jpg/500px-Norway_Italy_-_June_2025_E_04.jpg" },
      { name: "Gabriel Martinelli", position: "LW", nationality: "Brazil", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/200712.png" },
    ],
    recentNews: [
      { title: "Arteta praises Arsenal's intensity in North London derby win", tag: "Premier League", date: "2025-05-19" },
      { title: "Saka nominated for PFA Players' Player of the Year", tag: "Awards", date: "2025-05-12" },
      { title: "Arsenal target Champions League glory after stellar group stage", tag: "Champions League", date: "2025-05-05" },
    ],
    stats: [
      { label: "League Position", value: "3rd" },
      { label: "Goals Scored", value: "76" },
      { label: "Clean Sheets", value: "18" },
      { label: "Win Rate", value: "65%" },
    ],
    website: "https://www.arsenal.com",
  },

  33: {
    id: 33,
    name: "Manchester United",
    shortName: "Man United",
    logo: "https://media.api-sports.io/football/teams/33.png",
    country: "England",
    isNational: false,
    founded: 1878,
    stadium: "Old Trafford",
    stadiumCity: "Manchester",
    stadiumCapacity: 74310,
    manager: "Rúben Amorim",
    league: "Premier League",
    leagueLogo: "https://media.api-sports.io/football/leagues/39.png",
    primaryColor: "#DA291C",
    secondaryColor: "#FBE122",
    description: "Manchester United is one of the most famous and successful football clubs in the world, founded in 1878. Based at Old Trafford — 'The Theatre of Dreams' — United have won 20 league titles and 3 UEFA Champions Leagues under legendary managers including Sir Alex Ferguson.",
    trophies: [
      { name: "English Top Flight", count: 20 },
      { name: "UEFA Champions League", count: 3 },
      { name: "FA Cup", count: 13 },
      { name: "EFL Cup", count: 6 },
      { name: "UEFA Europa League", count: 1 },
    ],
    keyPlayers: [
      { name: "Marcus Rashford", position: "FW", nationality: "England", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/1/11/Marcus_Rashford_in_2023.jpg/500px-Marcus_Rashford_in_2023.jpg" },
      { name: "Bruno Fernandes", position: "CAM", nationality: "Portugal", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Bruno_Fernandes_USMNT_v_Portugal_Mar_31_2026-27_%28cropped%29.jpg/500px-Bruno_Fernandes_USMNT_v_Portugal_Mar_31_2026-27_%28cropped%29.jpg" },
      { name: "Rasmus Højlund", position: "ST", nationality: "Denmark", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/284442.png" },
    ],
    recentNews: [
      { title: "Amorim era: Manchester United look to rebuild under new manager", tag: "Club News", date: "2025-05-20" },
      { title: "Old Trafford redevelopment plans confirmed by INEOS ownership", tag: "Club News", date: "2025-05-15" },
      { title: "United eyeing summer transfers to revamp struggling squad", tag: "Transfer", date: "2025-05-08" },
    ],
    stats: [
      { label: "League Position", value: "8th" },
      { label: "Goals Scored", value: "52" },
      { label: "Clean Sheets", value: "9" },
      { label: "Win Rate", value: "42%" },
    ],
    website: "https://www.manutd.com",
  },

  49: {
    id: 49,
    name: "Chelsea F.C.",
    shortName: "Chelsea",
    logo: "https://media.api-sports.io/football/teams/49.png",
    country: "England",
    isNational: false,
    founded: 1905,
    stadium: "Stamford Bridge",
    stadiumCity: "London",
    stadiumCapacity: 40834,
    manager: "Enzo Maresca",
    league: "Premier League",
    leagueLogo: "https://media.api-sports.io/football/leagues/39.png",
    primaryColor: "#034694",
    secondaryColor: "#DBA111",
    description: "Chelsea F.C. is a professional football club based in Fulham, London, playing at Stamford Bridge. Founded in 1905, Chelsea has grown into a major global football brand, winning multiple Premier League titles and 2 UEFA Champions League trophies.",
    trophies: [
      { name: "Premier League", count: 6 },
      { name: "UEFA Champions League", count: 2 },
      { name: "FA Cup", count: 8 },
      { name: "EFL Cup", count: 5 },
      { name: "UEFA Europa League", count: 2 },
    ],
    keyPlayers: [
      { name: "Cole Palmer", position: "AM", nationality: "England", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/f/fb/Cole_Palmer_2025_FIFA_Club_World_Cup_Final.jpg" },
      { name: "Nicolas Jackson", position: "ST", nationality: "Senegal", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/284460.png" },
      { name: "Reece James", position: "RB", nationality: "England", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/284460.png" },
    ],
    recentNews: [
      { title: "Maresca targets top-four finish as Chelsea's young stars click", tag: "Premier League", date: "2025-05-18" },
      { title: "Cole Palmer's sensational season earns England senior call-up", tag: "Awards", date: "2025-05-11" },
      { title: "Chelsea in talks over new Stamford Bridge stadium development", tag: "Club News", date: "2025-05-05" },
    ],
    stats: [
      { label: "League Position", value: "6th" },
      { label: "Goals Scored", value: "69" },
      { label: "Clean Sheets", value: "11" },
      { label: "Win Rate", value: "52%" },
    ],
    website: "https://www.chelseafc.com",
  },

  541: {
    id: 541,
    name: "Real Madrid CF",
    shortName: "Real Madrid",
    logo: "https://media.api-sports.io/football/teams/541.png",
    country: "Spain",
    isNational: false,
    founded: 1902,
    stadium: "Estadio Santiago Bernabéu",
    stadiumCity: "Madrid",
    stadiumCapacity: 81044,
    manager: "Carlo Ancelotti",
    league: "La Liga",
    leagueLogo: "https://media.api-sports.io/football/leagues/140.png",
    primaryColor: "#FEBE10",
    secondaryColor: "#00529F",
    description: "Real Madrid C.F. is the most successful club in the history of the UEFA Champions League, having won the title a record 15 times. Founded in 1902 and based at the iconic Santiago Bernabéu stadium in Madrid, Los Blancos are consistently regarded as the greatest football club in the world.",
    trophies: [
      { name: "UEFA Champions League", count: 15 },
      { name: "La Liga", count: 36 },
      { name: "Copa del Rey", count: 20 },
      { name: "FIFA Club World Cup", count: 8 },
      { name: "UEFA Super Cup", count: 5 },
    ],
    keyPlayers: [
      { name: "Kylian Mbappé", position: "ST", nationality: "France", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Kylian_Mbapp%C3%A9_2023.jpg/500px-Kylian_Mbapp%C3%A9_2023.jpg" },
      { name: "Jude Bellingham", position: "CM", nationality: "England", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/f/f9/25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Jude_Bellingham_-_240422_190551-2_%28cropped%29.jpg/500px-25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Jude_Bellingham_-_240422_190551-2_%28cropped%29.jpg" },
      { name: "Vinícius Júnior", position: "LW", nationality: "Brazil", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/c/c6/2023_05_06_Final_de_la_Copa_del_Rey_-_52879242230_%28cropped%29.jpg/500px-2023_05_06_Final_de_la_Copa_del_Rey_-_52879242230_%28cropped%29.jpg" },
    ],
    recentNews: [
      { title: "Real Madrid's Mbappé and Vinicius fire Blancos to La Liga summit", tag: "La Liga", date: "2025-05-20" },
      { title: "Bellingham named UEFA Player of the Year after brilliant season", tag: "Awards", date: "2025-05-13" },
      { title: "Bernabéu renovation complete: the world's most modern stadium", tag: "Club News", date: "2025-05-07" },
    ],
    stats: [
      { label: "League Position", value: "1st" },
      { label: "Goals Scored", value: "93" },
      { label: "Clean Sheets", value: "22" },
      { label: "Win Rate", value: "79%" },
    ],
    website: "https://www.realmadrid.com",
  },

  529: {
    id: 529,
    name: "FC Barcelona",
    shortName: "Barcelona",
    logo: "https://media.api-sports.io/football/teams/529.png",
    country: "Spain",
    isNational: false,
    founded: 1899,
    stadium: "Estadi Olímpic Lluís Companys",
    stadiumCity: "Barcelona",
    stadiumCapacity: 54367,
    manager: "Hansi Flick",
    league: "La Liga",
    leagueLogo: "https://media.api-sports.io/football/leagues/140.png",
    primaryColor: "#A50044",
    secondaryColor: "#004D98",
    description: "FC Barcelona is one of the world's most famous sports clubs, founded in 1899. Known as 'Més que un club' (More than a club), Barcelona has produced legends like Johan Cruyff, Ronaldinho, Xavi, Iniesta, and Lionel Messi. They play at Estadi Olímpic while Camp Nou is being renovated.",
    trophies: [
      { name: "UEFA Champions League", count: 5 },
      { name: "La Liga", count: 27 },
      { name: "Copa del Rey", count: 31 },
      { name: "FIFA Club World Cup", count: 3 },
      { name: "UEFA Super Cup", count: 5 },
    ],
    keyPlayers: [
      { name: "Lamine Yamal", position: "RW", nationality: "Spain", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Lamine_Yamal_in_2025.jpg/500px-Lamine_Yamal_in_2025.jpg" },
      { name: "Raphinha", position: "RW", nationality: "Brazil", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Raphael_Dias_Belloli_2023.jpg/500px-Raphael_Dias_Belloli_2023.jpg" },
      { name: "Robert Lewandowski", position: "ST", nationality: "Poland", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/2/26/2019147183134_2019-05-27_Fussball_1.FC_Kaiserslautern_vs_FC_Bayern_M%C3%BCnchen_-_Sven_-_1D_X_MK_II_-_0228_-_B70I8527_%28cropped%29.jpg/500px-2019147183134_2019-05-27_Fussball_1.FC_Kaiserslautern_vs_FC_Bayern_M%C3%BCnchen_-_Sven_-_1D_X_MK_II_-_0228_-_B70I8527_%28cropped%29.jpg" },
    ],
    recentNews: [
      { title: "Flick's Barcelona dazzle with tiki-taka revival in La Liga", tag: "La Liga", date: "2025-05-19" },
      { title: "Lamine Yamal, 17, named La Liga's best young player", tag: "Awards", date: "2025-05-12" },
      { title: "Camp Nou renovation on track for 2026 World Cup opener", tag: "Club News", date: "2025-05-05" },
    ],
    stats: [
      { label: "League Position", value: "2nd" },
      { label: "Goals Scored", value: "87" },
      { label: "Clean Sheets", value: "16" },
      { label: "Win Rate", value: "71%" },
    ],
    website: "https://www.fcbarcelona.com",
  },

  157: {
    id: 157,
    name: "FC Bayern Munich",
    shortName: "Bayern",
    logo: "https://media.api-sports.io/football/teams/157.png",
    country: "Germany",
    isNational: false,
    founded: 1900,
    stadium: "Allianz Arena",
    stadiumCity: "Munich",
    stadiumCapacity: 75024,
    manager: "Vincent Kompany",
    league: "Bundesliga",
    leagueLogo: "https://media.api-sports.io/football/leagues/78.png",
    primaryColor: "#DC052D",
    secondaryColor: "#0066B2",
    description: "FC Bayern Munich is Germany's most successful football club and one of the richest in the world. Founded in 1900 and playing at the iconic Allianz Arena in Munich, Bayern have won the Bundesliga a record 33 times and the Champions League 6 times.",
    trophies: [
      { name: "Bundesliga", count: 33 },
      { name: "UEFA Champions League", count: 6 },
      { name: "DFB-Pokal", count: 20 },
      { name: "FIFA Club World Cup", count: 2 },
      { name: "UEFA Super Cup", count: 2 },
    ],
    keyPlayers: [
      { name: "Harry Kane", position: "ST", nationality: "England", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/9/91/Harry_Kane_on_October_10%2C_2023.jpg/500px-Harry_Kane_on_October_10%2C_2023.jpg" },
      { name: "Jamal Musiala", position: "AM", nationality: "Germany", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/4/44/Jamal_Musiala_2022_%28cropped%29.jpg" },
      { name: "Leroy Sané", position: "RW", nationality: "Germany", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/2317.png" },
    ],
    recentNews: [
      { title: "Kompany's Bayern Munich set for Bundesliga title comeback", tag: "Bundesliga", date: "2025-05-20" },
      { title: "Kane breaks Bundesliga scoring record in record time", tag: "Stats", date: "2025-05-14" },
      { title: "Bayern agree deal for top Austrian midfield talent", tag: "Transfer", date: "2025-05-07" },
    ],
    stats: [
      { label: "League Position", value: "1st" },
      { label: "Goals Scored", value: "94" },
      { label: "Clean Sheets", value: "16" },
      { label: "Win Rate", value: "74%" },
    ],
    website: "https://fcbayern.com",
  },

  496: {
    id: 496,
    name: "Juventus F.C.",
    shortName: "Juventus",
    logo: "https://media.api-sports.io/football/teams/496.png",
    country: "Italy",
    isNational: false,
    founded: 1897,
    stadium: "Allianz Stadium",
    stadiumCity: "Turin",
    stadiumCapacity: 41507,
    manager: "Thiago Motta",
    league: "Serie A",
    leagueLogo: "https://media.api-sports.io/football/leagues/135.png",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    description: "Juventus F.C. is Italy's most successful club and one of the most famous clubs in the world. Founded in 1897 and based in Turin, 'The Old Lady' have won the Serie A title a record 36 times and 2 UEFA Champions Leagues. They play at the modern Allianz Stadium.",
    trophies: [
      { name: "Serie A", count: 36 },
      { name: "UEFA Champions League", count: 2 },
      { name: "Coppa Italia", count: 15 },
      { name: "UEFA Cup Winners' Cup", count: 1 },
      { name: "Club World Cup / Intercontinental Cup", count: 2 },
    ],
    keyPlayers: [
      { name: "Dušan Vlahović", position: "ST", nationality: "Serbia", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/236376.png" },
      { name: "Teun Koopmeiners", position: "AM", nationality: "Netherlands", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/152912.png" },
      { name: "Kenan Yıldız", position: "LW", nationality: "Turkey", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/341999.png" },
    ],
    recentNews: [
      { title: "Thiago Motta's Juventus show promise in new Serie A campaign", tag: "Serie A", date: "2025-05-18" },
      { title: "Vlahovic hits 20 Serie A goals for the season", tag: "Stats", date: "2025-05-11" },
      { title: "Juventus linked with summer move for top European midfielder", tag: "Transfer", date: "2025-05-04" },
    ],
    stats: [
      { label: "League Position", value: "4th" },
      { label: "Goals Scored", value: "62" },
      { label: "Clean Sheets", value: "14" },
      { label: "Win Rate", value: "55%" },
    ],
    website: "https://www.juventus.com",
  },

  489: {
    id: 489,
    name: "AC Milan",
    shortName: "AC Milan",
    logo: "https://media.api-sports.io/football/teams/489.png",
    country: "Italy",
    isNational: false,
    founded: 1899,
    stadium: "San Siro (Stadio Giuseppe Meazza)",
    stadiumCity: "Milan",
    stadiumCapacity: 75923,
    manager: "Paulo Fonseca",
    league: "Serie A",
    leagueLogo: "https://media.api-sports.io/football/leagues/135.png",
    primaryColor: "#FB090B",
    secondaryColor: "#000000",
    description: "AC Milan is one of the most iconic clubs in world football, founded in 1899. Playing at San Siro in Milan alongside city rivals Inter, Milan are a record 7-time UEFA Champions League winners and have 19 Serie A titles to their name.",
    trophies: [
      { name: "Serie A", count: 19 },
      { name: "UEFA Champions League", count: 7 },
      { name: "Coppa Italia", count: 5 },
      { name: "FIFA Club World Cup", count: 4 },
      { name: "UEFA Super Cup", count: 5 },
    ],
    keyPlayers: [
      { name: "Rafael Leão", position: "LW", nationality: "Portugal", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/207282.png" },
      { name: "Christian Pulisic", position: "RW", nationality: "USA", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/5/52/Christian_Pulisic_2024_%28cropped%29.jpg/500px-Christian_Pulisic_2024_%28cropped%29.jpg" },
      { name: "Mike Maignan", position: "GK", nationality: "France", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/26477.png" },
    ],
    recentNews: [
      { title: "Leão's brilliance drives AC Milan's European ambitions", tag: "Champions League", date: "2025-05-17" },
      { title: "New San Siro stadium decision expected before end of season", tag: "Club News", date: "2025-05-10" },
      { title: "Milan bring in key summer signings to strengthen squad depth", tag: "Transfer", date: "2025-05-03" },
    ],
    stats: [
      { label: "League Position", value: "3rd" },
      { label: "Goals Scored", value: "71" },
      { label: "Clean Sheets", value: "13" },
      { label: "Win Rate", value: "58%" },
    ],
    website: "https://www.acmilan.com",
  },

  505: {
    id: 505,
    name: "Inter Milan",
    shortName: "Inter",
    logo: "https://media.api-sports.io/football/teams/505.png",
    country: "Italy",
    isNational: false,
    founded: 1908,
    stadium: "San Siro (Stadio Giuseppe Meazza)",
    stadiumCity: "Milan",
    stadiumCapacity: 75923,
    manager: "Simone Inzaghi",
    league: "Serie A",
    leagueLogo: "https://media.api-sports.io/football/leagues/135.png",
    primaryColor: "#003DA5",
    secondaryColor: "#000000",
    description: "FC Internazionale Milano, known as Inter Milan, was founded in 1908. The only Italian club never to have been relegated from Serie A, they share San Siro with AC Milan. Inter have won 20 Serie A titles and the treble in 2010 under Jose Mourinho.",
    trophies: [
      { name: "Serie A", count: 20 },
      { name: "UEFA Champions League", count: 3 },
      { name: "Coppa Italia", count: 9 },
      { name: "UEFA Cup", count: 3 },
      { name: "FIFA Club World Cup", count: 2 },
    ],
    keyPlayers: [
      { name: "Lautaro Martínez", position: "ST", nationality: "Argentina", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/34538.png" },
      { name: "Nicolò Barella", position: "CM", nationality: "Italy", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/19318.png" },
      { name: "Marcus Thuram", position: "ST", nationality: "France", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/2326.png" },
    ],
    recentNews: [
      { title: "Inter Milan retain Serie A title with dominant campaign", tag: "Serie A", date: "2025-05-20" },
      { title: "Lautaro Martínez: from Buenos Aires to Serie A top scorer", tag: "Profile", date: "2025-05-12" },
      { title: "Inter planning major renovations to San Siro for 2026", tag: "Club News", date: "2025-05-05" },
    ],
    stats: [
      { label: "League Position", value: "1st" },
      { label: "Goals Scored", value: "88" },
      { label: "Clean Sheets", value: "23" },
      { label: "Win Rate", value: "76%" },
    ],
    website: "https://www.inter.it",
  },

  492: {
    id: 492,
    name: "S.S.C. Napoli",
    shortName: "Napoli",
    logo: "/napoli.png",
    country: "Italy",
    isNational: false,
    founded: 1926,
    stadium: "Stadio Diego Armando Maradona",
    stadiumCity: "Naples",
    stadiumCapacity: 54726,
    manager: "Antonio Conte",
    league: "Serie A",
    leagueLogo: "https://media.api-sports.io/football/leagues/135.png",
    primaryColor: "#12A0C3",
    secondaryColor: "#003DA5",
    description: "S.S.C. Napoli is a professional football club based in Naples, Italy, founded in 1926. The club's stadium was renamed in honour of Diego Maradona, who inspired Napoli to their greatest era in the 1980s. They won their third Serie A title in 2023 under Luciano Spalletti.",
    trophies: [
      { name: "Serie A", count: 3 },
      { name: "Coppa Italia", count: 6 },
      { name: "UEFA Cup", count: 1 },
      { name: "Supercoppa Italiana", count: 2 },
    ],
    keyPlayers: [
      { name: "Romelu Lukaku", position: "ST", nationality: "Belgium", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Romelu_Lukaku_2021.jpg/500px-Romelu_Lukaku_2021.jpg" },
      { name: "Khvicha Kvaratskhelia", position: "LW", nationality: "Georgia", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/236264.png" },
      { name: "Giovanni Di Lorenzo", position: "RB", nationality: "Italy", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/18780.png" },
    ],
    recentNews: [
      { title: "Conte's Napoli look ominous as they push for Serie A title", tag: "Serie A", date: "2025-05-19" },
      { title: "Osimhen saga continues as Napoli reject PSG's huge offer", tag: "Transfer", date: "2025-05-11" },
      { title: "Maradona legacy lives on: Napoli fans celebrate at renamed stadium", tag: "Club News", date: "2025-05-04" },
    ],
    stats: [
      { label: "League Position", value: "2nd" },
      { label: "Goals Scored", value: "74" },
      { label: "Clean Sheets", value: "15" },
      { label: "Win Rate", value: "61%" },
    ],
    website: "https://www.sscnapoli.it",
  },

  85: {
    id: 85,
    name: "Paris Saint-Germain F.C.",
    shortName: "PSG",
    logo: "https://media.api-sports.io/football/teams/85.png",
    country: "France",
    isNational: false,
    founded: 1970,
    stadium: "Parc des Princes",
    stadiumCity: "Paris",
    stadiumCapacity: 47929,
    manager: "Luis Enrique",
    league: "Ligue 1",
    leagueLogo: "https://media.api-sports.io/football/leagues/61.png",
    primaryColor: "#004170",
    secondaryColor: "#DA291C",
    description: "Paris Saint-Germain F.C. is France's most successful club and one of the richest in world football following the Qatar Sports Investments takeover in 2011. Based at Parc des Princes, PSG have dominated Ligue 1 and have attracted global superstars including Messi, Neymar and Mbappé.",
    trophies: [
      { name: "Ligue 1", count: 12 },
      { name: "Coupe de France", count: 15 },
      { name: "Coupe de la Ligue", count: 9 },
      { name: "UEFA Champions League Final", count: 1 },
      { name: "Trophée des Champions", count: 12 },
    ],
    keyPlayers: [
      { name: "Ousmane Dembélé", position: "RW", nationality: "France", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/7195.png" },
      { name: "Bradley Barcola", position: "LW", nationality: "France", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/284455.png" },
      { name: "Marquinhos", position: "CB", nationality: "Brazil", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/1053.png" },
    ],
    recentNews: [
      { title: "PSG thrive post-Mbappé with exciting new generation", tag: "Ligue 1", date: "2025-05-18" },
      { title: "Luis Enrique builds brilliant new squad around French talent", tag: "Club News", date: "2025-05-12" },
      { title: "PSG advance to Champions League semi-final with stunning victory", tag: "Champions League", date: "2025-05-05" },
    ],
    stats: [
      { label: "League Position", value: "1st" },
      { label: "Goals Scored", value: "82" },
      { label: "Clean Sheets", value: "18" },
      { label: "Win Rate", value: "71%" },
    ],
    website: "https://en.psg.fr",
  },

  190: {
    id: 190,
    name: "SL Benfica",
    shortName: "Benfica",
    logo: "/benfica.png",
    country: "Portugal",
    isNational: false,
    founded: 1904,
    stadium: "Estádio da Luz",
    stadiumCity: "Lisbon",
    stadiumCapacity: 64642,
    manager: "Bruno Lage",
    league: "Primeira Liga",
    leagueLogo: "https://media.api-sports.io/football/leagues/94.png",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
    description: "Sport Lisboa e Benfica, simply known as Benfica, is Portugal's most successful and most supported football club. Founded in 1904, the Eagles play at Estádio da Luz in Lisbon and are the most-titled club in Portuguese football history with 38 Primeira Liga titles.",
    trophies: [
      { name: "Primeira Liga", count: 38 },
      { name: "UEFA Champions League", count: 2 },
      { name: "Taça de Portugal", count: 26 },
      { name: "Supertaça Cândido de Oliveira", count: 9 },
    ],
    keyPlayers: [
      { name: "Angel Di María", position: "RW", nationality: "Argentina", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/293.png" },
      { name: "Orkun Kökçü", position: "CM", nationality: "Netherlands", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/155442.png" },
      { name: "Fredrik Aursnes", position: "DM", nationality: "Norway", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/168530.png" },
    ],
    recentNews: [
      { title: "Benfica hunt down Sporting CP in Primeira Liga title race", tag: "Primeira Liga", date: "2025-05-19" },
      { title: "Estádio da Luz named as 2025 Champions League final venue", tag: "Champions League", date: "2025-05-12" },
      { title: "Young Benfica stars attract interest from Premier League clubs", tag: "Transfer", date: "2025-05-04" },
    ],
    stats: [
      { label: "League Position", value: "2nd" },
      { label: "Goals Scored", value: "77" },
      { label: "Clean Sheets", value: "16" },
      { label: "Win Rate", value: "68%" },
    ],
    website: "https://www.slbenfica.pt",
  },

  192: {
    id: 192,
    name: "FC Porto",
    shortName: "FC Porto",
    logo: "/porto.png",
    country: "Portugal",
    isNational: false,
    founded: 1893,
    stadium: "Estádio do Dragão",
    stadiumCity: "Porto",
    stadiumCapacity: 50033,
    manager: "Vítor Bruno",
    league: "Primeira Liga",
    leagueLogo: "https://media.api-sports.io/football/leagues/94.png",
    primaryColor: "#003DA5",
    secondaryColor: "#FFFFFF",
    description: "FC Porto is one of Portugal's most successful clubs and a powerhouse of European football. Founded in 1893, they play at Estádio do Dragão and famously won back-to-back UEFA Champions Leagues in 1987 and 2004 under José Mourinho.",
    trophies: [
      { name: "Primeira Liga", count: 30 },
      { name: "UEFA Champions League", count: 2 },
      { name: "UEFA Cup", count: 1 },
      { name: "Taça de Portugal", count: 19 },
      { name: "FIFA Club World Cup", count: 1 },
    ],
    keyPlayers: [
      { name: "Diogo Costa", position: "GK", nationality: "Portugal", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/284.png" },
      { name: "Alan Varela", position: "DM", nationality: "Argentina", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/12345.png" },
      { name: "Galeno", position: "LW", nationality: "Brazil", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/88750.png" },
    ],
    recentNews: [
      { title: "FC Porto lead Primeira Liga title race ahead of Benfica", tag: "Primeira Liga", date: "2025-05-20" },
      { title: "Porto's Champions League run ends in dramatic quarter-final defeat", tag: "Champions League", date: "2025-05-13" },
      { title: "Dragão celebrates 30 years of Primeira Liga dominance", tag: "Club News", date: "2025-05-05" },
    ],
    stats: [
      { label: "League Position", value: "1st" },
      { label: "Goals Scored", value: "80" },
      { label: "Clean Sheets", value: "19" },
      { label: "Win Rate", value: "72%" },
    ],
    website: "https://www.fcporto.pt",
  },

  193: {
    id: 193,
    name: "Sporting CP",
    shortName: "Sporting",
    logo: "/sporting.png",
    country: "Portugal",
    isNational: false,
    founded: 1906,
    stadium: "Estádio José Alvalade",
    stadiumCity: "Lisbon",
    stadiumCapacity: 50466,
    manager: "João Pereira",
    league: "Primeira Liga",
    leagueLogo: "https://media.api-sports.io/football/leagues/94.png",
    primaryColor: "#00803E",
    secondaryColor: "#FFFFFF",
    description: "Sporting Clube de Portugal, known as Sporting CP or The Lions, is one of Portugal's Big Three football clubs. Founded in 1906, they play at Estádio José Alvalade in Lisbon and are famous for their Academy, which has produced Cristiano Ronaldo, Luís Figo, and many other world-class players.",
    trophies: [
      { name: "Primeira Liga", count: 19 },
      { name: "Taça de Portugal", count: 17 },
      { name: "UEFA Cup Winners' Cup", count: 1 },
      { name: "Supertaça Cândido de Oliveira", count: 9 },
    ],
    keyPlayers: [
      { name: "Pedro Gonçalves", position: "AM", nationality: "Portugal", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/152036.png" },
      { name: "Viktor Gyökeres", position: "ST", nationality: "Sweden", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/176949.png" },
      { name: "Marcus Edwards", position: "RW", nationality: "England", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/203524.png" },
    ],
    recentNews: [
      { title: "Gyökeres breaks Sporting scoring record in title challenge", tag: "Primeira Liga", date: "2025-05-18" },
      { title: "Sporting's famous academy produces another talent for top European clubs", tag: "Transfer", date: "2025-05-11" },
      { title: "Lions roar: Sporting end run at Europa League quarter-finals", tag: "Europa League", date: "2025-05-04" },
    ],
    stats: [
      { label: "League Position", value: "3rd" },
      { label: "Goals Scored", value: "82" },
      { label: "Clean Sheets", value: "14" },
      { label: "Win Rate", value: "65%" },
    ],
    website: "https://www.sporting.pt",
  },

  1595: {
    id: 1595,
    name: "Inter Miami CF",
    shortName: "Inter Miami",
    logo: "/inter-miami.png",
    country: "USA",
    isNational: false,
    founded: 2018,
    stadium: "Chase Stadium",
    stadiumCity: "Fort Lauderdale, Florida",
    stadiumCapacity: 21550,
    manager: "Javier Mascherano",
    league: "MLS",
    leagueLogo: "https://media.api-sports.io/football/leagues/253.png",
    primaryColor: "#F7B5CD",
    secondaryColor: "#231F20",
    description: "Inter Miami CF is a Major League Soccer club co-founded by David Beckham, based in Fort Lauderdale, Florida. Founded in 2018 and playing since 2020, the club gained global attention when Lionel Messi, the greatest footballer of all time, joined in 2023. They play at Chase Stadium.",
    trophies: [
      { name: "Leagues Cup", count: 1 },
      { name: "Supporters' Shield", count: 1 },
    ],
    keyPlayers: [
      { name: "Lionel Messi", position: "RW", nationality: "Argentina", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/154.png" },
      { name: "Sergio Busquets", position: "DM", nationality: "Spain", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/231.png" },
      { name: "Jordi Alba", position: "LB", nationality: "Spain", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/394.png" },
    ],
    recentNews: [
      { title: "Messi magic continues as Inter Miami lead Eastern Conference", tag: "MLS", date: "2025-05-20" },
      { title: "Inter Miami's new stadium plans revealed ahead of 2026 World Cup", tag: "Club News", date: "2025-05-13" },
      { title: "Suárez farewell: Miami fans celebrate club legend's career", tag: "Club News", date: "2025-05-06" },
    ],
    stats: [
      { label: "League Position", value: "1st (East)" },
      { label: "Goals Scored", value: "58" },
      { label: "Clean Sheets", value: "12" },
      { label: "Win Rate", value: "61%" },
    ],
    website: "https://www.intermiamicf.com",
  },

  2939: {
    id: 2939,
    name: "Al Nassr FC",
    shortName: "Al Nassr",
    logo: "https://media.api-sports.io/football/teams/2939.png",
    country: "Saudi Arabia",
    isNational: false,
    founded: 1955,
    stadium: "Al-Awwal Park",
    stadiumCity: "Riyadh",
    stadiumCapacity: 25000,
    manager: "Stefano Pioli",
    league: "Saudi Pro League",
    leagueLogo: "https://media.api-sports.io/football/leagues/307.png",
    primaryColor: "#FFDD00",
    secondaryColor: "#003DA5",
    description: "Al Nassr FC is a Saudi Arabian football club founded in 1955, based in Riyadh. The club made global headlines in January 2023 when Portuguese superstar Cristiano Ronaldo signed for the club. Al Nassr play at Al-Awwal Park and are one of the most decorated clubs in Saudi football history.",
    trophies: [
      { name: "Saudi Pro League", count: 9 },
      { name: "King Cup", count: 6 },
      { name: "Crown Prince Cup", count: 5 },
      { name: "Saudi Super Cup", count: 1 },
    ],
    keyPlayers: [
      { name: "Cristiano Ronaldo", position: "ST", nationality: "Portugal", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/874.png" },
      { name: "Sadio Mané", position: "LW", nationality: "Senegal", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/4/49/Sadio_Man%C3%A9_-_2022.jpg/500px-Sadio_Man%C3%A9_-_2022.jpg" },
      { name: "Aymeric Laporte", position: "CB", nationality: "Spain", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/2935.png" },
    ],
    recentNews: [
      { title: "Ronaldo nets 50th goal of the season for Al Nassr", tag: "Saudi Pro League", date: "2025-05-18" },
      { title: "Al Nassr in Saudi Pro League title race with Al Hilal", tag: "Saudi Pro League", date: "2025-05-11" },
      { title: "Al Nassr to play in 2025 FIFA Club World Cup in USA", tag: "Club News", date: "2025-05-04" },
    ],
    stats: [
      { label: "League Position", value: "2nd" },
      { label: "Goals Scored", value: "86" },
      { label: "Clean Sheets", value: "11" },
      { label: "Win Rate", value: "66%" },
    ],
    website: "https://www.alnassr.com.sa",
  },

  2931: {
    id: 2931,
    name: "Al Hilal SFC",
    shortName: "Al Hilal",
    logo: "/al-hilal-new.png",
    country: "Saudi Arabia",
    isNational: false,
    founded: 1957,
    stadium: "Kingdom Arena",
    stadiumCity: "Riyadh",
    stadiumCapacity: 47006,
    manager: "Jorge Jesus",
    league: "Saudi Pro League",
    leagueLogo: "https://media.api-sports.io/football/leagues/307.png",
    primaryColor: "#003DA5",
    secondaryColor: "#FFFFFF",
    description: "Al Hilal SFC is the most decorated football club in Asia, founded in 1957 in Riyadh. They play at Kingdom Arena and have won the Asian Champions League a record 4 times. Al Hilal gained international attention by signing Neymar Jr in 2023 and have consistently dominated the Saudi Pro League.",
    trophies: [
      { name: "Saudi Pro League", count: 19 },
      { name: "AFC Champions League", count: 4 },
      { name: "King Cup", count: 10 },
      { name: "Arab Club Champions Cup", count: 5 },
    ],
    keyPlayers: [
      { name: "Neymar Jr", position: "FW", nationality: "Brazil", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/278.png" },
      { name: "Rúben Neves", position: "DM", nationality: "Portugal", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/9713.png" },
      { name: "Aleksandar Mitrović", position: "ST", nationality: "Serbia", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/1163.png" },
    ],
    recentNews: [
      { title: "Al Hilal clinch Saudi Pro League title in record-breaking fashion", tag: "Saudi Pro League", date: "2025-05-20" },
      { title: "Neymar returns to training after long-term injury", tag: "Injury", date: "2025-05-12" },
      { title: "Al Hilal to face European giants in Club World Cup USA 2025", tag: "Club News", date: "2025-05-05" },
    ],
    stats: [
      { label: "League Position", value: "1st" },
      { label: "Goals Scored", value: "94" },
      { label: "Clean Sheets", value: "18" },
      { label: "Win Rate", value: "79%" },
    ],
    website: "https://www.alhilal.com",
  },

  451: {
    id: 451,
    name: "Boca Juniors",
    shortName: "Boca",
    logo: "https://media.api-sports.io/football/teams/451.png",
    country: "Argentina",
    isNational: false,
    founded: 1905,
    stadium: "Estadio Alberto J. Armando (La Bombonera)",
    stadiumCity: "Buenos Aires",
    stadiumCapacity: 54000,
    manager: "Fernando Gago",
    league: "Argentine Primera División",
    leagueLogo: "https://media.api-sports.io/football/leagues/128.png",
    primaryColor: "#003DA5",
    secondaryColor: "#FFDD00",
    description: "Club Atlético Boca Juniors is one of the most famous football clubs in the world, founded in 1905 in the La Boca neighbourhood of Buenos Aires. Their stadium, La Bombonera, is one of the most intimidating venues in football. Boca have won 6 Copa Libertadores and produced legends like Maradona and Tevez.",
    trophies: [
      { name: "Argentine Primera División", count: 35 },
      { name: "Copa Libertadores", count: 6 },
      { name: "Intercontinental Cup", count: 3 },
      { name: "Copa Argentina", count: 5 },
    ],
    keyPlayers: [
      { name: "Edinson Cavani", position: "ST", nationality: "Uruguay", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/357.png" },
      { name: "Marcos Rojo", position: "CB", nationality: "Argentina", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/1102.png" },
      { name: "Luis Advíncula", position: "RB", nationality: "Peru", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/2490.png" },
    ],
    recentNews: [
      { title: "La Bombonera erupts as Boca Juniors edge city rivals Racing", tag: "Argentine Football", date: "2025-05-19" },
      { title: "Cavani shines for Boca in Copa Libertadores opener", tag: "Copa Libertadores", date: "2025-05-11" },
      { title: "Superclásico confirmed: Boca host River Plate in historic showdown", tag: "Superclásico", date: "2025-05-03" },
    ],
    stats: [
      { label: "League Position", value: "3rd" },
      { label: "Goals Scored", value: "47" },
      { label: "Clean Sheets", value: "10" },
      { label: "Win Rate", value: "55%" },
    ],
    website: "https://www.bocajuniors.com.ar",
  },

  435: {
    id: 435,
    name: "River Plate",
    shortName: "River",
    logo: "https://media.api-sports.io/football/teams/435.png",
    country: "Argentina",
    isNational: false,
    founded: 1901,
    stadium: "El Monumental",
    stadiumCity: "Buenos Aires",
    stadiumCapacity: 84567,
    manager: "Marcelo Gallardo",
    league: "Argentine Primera División",
    leagueLogo: "https://media.api-sports.io/football/leagues/128.png",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    description: "Club Atlético River Plate is one of Argentina's and South America's most successful football clubs, founded in 1901. El Monumental is the largest stadium in Argentina with over 84,000 seats. River Plate have won the Copa Libertadores 4 times and are the fiercest rivals of Boca Juniors in the famous Superclásico.",
    trophies: [
      { name: "Argentine Primera División", count: 38 },
      { name: "Copa Libertadores", count: 4 },
      { name: "Intercontinental Cup", count: 1 },
      { name: "Recopa Sudamericana", count: 4 },
    ],
    keyPlayers: [
      { name: "Pablo Solari", position: "RW", nationality: "Argentina", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/378282.png" },
      { name: "Nacho Fernández", position: "AM", nationality: "Argentina", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/6228.png" },
      { name: "Franco Armani", position: "GK", nationality: "Argentina", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/6128.png" },
    ],
    recentNews: [
      { title: "Gallardo back at River: The Machine returns to El Monumental", tag: "Argentine Football", date: "2025-05-20" },
      { title: "River Plate begin Copa Libertadores defence in style", tag: "Copa Libertadores", date: "2025-05-12" },
      { title: "El Monumental renovation complete for World Cup 2030 bid", tag: "Club News", date: "2025-05-04" },
    ],
    stats: [
      { label: "League Position", value: "1st" },
      { label: "Goals Scored", value: "56" },
      { label: "Clean Sheets", value: "13" },
      { label: "Win Rate", value: "65%" },
    ],
    website: "https://www.cariverplate.com.ar",
  },

  // ── NATIONAL TEAMS ────────────────────────────────────────────────────────

  26: {
    id: 26,
    name: "Argentina",
    shortName: "Argentina",
    logo: "https://media.api-sports.io/football/teams/26.png",
    country: "World",
    isNational: true,
    founded: 1893,
    stadium: "Estadio Monumental",
    stadiumCity: "Buenos Aires",
    stadiumCapacity: 84567,
    manager: "Lionel Scaloni",
    primaryColor: "#74ACDF",
    secondaryColor: "#FFFFFF",
    description: "Argentina's national football team is the reigning FIFA World Cup champion, having won the 2022 World Cup in Qatar. The Albiceleste are one of football's greatest nations with 3 World Cup titles (1978, 1986, 2022), captained by the greatest player in history, Lionel Messi.",
    trophies: [
      { name: "FIFA World Cup", count: 3 },
      { name: "Copa América", count: 16 },
      { name: "FIFA Confederations Cup", count: 1 },
      { name: "Olympic Gold Medal", count: 2 },
    ],
    keyPlayers: [
      { name: "Lionel Messi", position: "FW", nationality: "Argentina", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/154.png" },
      { name: "Julián Álvarez", position: "ST", nationality: "Argentina", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/406086.png" },
      { name: "Rodrigo De Paul", position: "CM", nationality: "Argentina", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/6435.png" },
    ],
    recentNews: [
      { title: "Argentina prepare for 2026 World Cup title defence with dominant displays", tag: "World Cup", date: "2025-05-20" },
      { title: "Scaloni names Copa América-winning squad for upcoming qualifiers", tag: "International", date: "2025-05-13" },
      { title: "Messi's Argentina: How they plan to defend their World Cup crown", tag: "Analysis", date: "2025-05-06" },
    ],
    stats: [
      { label: "FIFA Ranking", value: "#1" },
      { label: "World Cups Won", value: "3" },
      { label: "Copa Américas", value: "16" },
      { label: "Confederations Cups", value: "1" },
    ],
  },

  6: {
    id: 6,
    name: "Brazil",
    shortName: "Brazil",
    logo: "https://media.api-sports.io/football/teams/6.png",
    country: "World",
    isNational: true,
    founded: 1914,
    stadium: "Maracanã",
    stadiumCity: "Rio de Janeiro",
    stadiumCapacity: 78838,
    manager: "Dorival Júnior",
    primaryColor: "#009C3B",
    secondaryColor: "#FFDF00",
    description: "Brazil is the most successful nation in FIFA World Cup history, having won the trophy a record 5 times (1958, 1962, 1970, 1994, 2002). The Seleção have produced the game's greatest ever players including Pelé, Ronaldo, Ronaldinho, Zico, and Cafu.",
    trophies: [
      { name: "FIFA World Cup", count: 5 },
      { name: "Copa América", count: 9 },
      { name: "FIFA Confederations Cup", count: 4 },
      { name: "Olympic Gold Medal", count: 2 },
    ],
    keyPlayers: [
      { name: "Vinícius Júnior", position: "LW", nationality: "Brazil", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/c/c6/2023_05_06_Final_de_la_Copa_del_Rey_-_52879242230_%28cropped%29.jpg/500px-2023_05_06_Final_de_la_Copa_del_Rey_-_52879242230_%28cropped%29.jpg" },
      { name: "Neymar Jr", position: "FW", nationality: "Brazil", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/b/bb/Neymar_Jr._with_Al_Hilal%2C_3_October_2023_-_03_%28cropped%29.jpg" },
      { name: "Rodrygo", position: "RW", nationality: "Brazil", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/198029.png" },
    ],
    recentNews: [
      { title: "Brazil eye 6th World Cup with new generation of talent in 2026", tag: "World Cup", date: "2025-05-19" },
      { title: "Vinicius Jr named South American Player of the Year", tag: "Awards", date: "2025-05-11" },
      { title: "Seleção's 2026 World Cup qualifying campaign back on track", tag: "CONMEBOL", date: "2025-05-04" },
    ],
    stats: [
      { label: "FIFA Ranking", value: "#5" },
      { label: "World Cups Won", value: "5" },
      { label: "Copa Américas", value: "9" },
      { label: "World Cup Appearances", value: "22" },
    ],
  },

  2: {
    id: 2,
    name: "France",
    shortName: "France",
    logo: "https://media.api-sports.io/football/teams/2.png",
    country: "World",
    isNational: true,
    founded: 1904,
    stadium: "Stade de France",
    stadiumCity: "Saint-Denis, Paris",
    stadiumCapacity: 80698,
    manager: "Didier Deschamps",
    primaryColor: "#003189",
    secondaryColor: "#FFFFFF",
    description: "France is one of football's great powers, having won 2 FIFA World Cups (1998 and 2018). Les Bleus play at the Stade de France and boast an exceptional squad with world-class talent including Kylian Mbappé, who is widely regarded as the sport's next global superstar.",
    trophies: [
      { name: "FIFA World Cup", count: 2 },
      { name: "UEFA Euro Championship", count: 2 },
      { name: "FIFA Confederations Cup", count: 2 },
      { name: "Olympic Gold Medal", count: 1 },
    ],
    keyPlayers: [
      { name: "Kylian Mbappé", position: "ST", nationality: "France", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/276.png" },
      { name: "Ousmane Dembélé", position: "RW", nationality: "France", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/7195.png" },
      { name: "Aurélien Tchouaméni", position: "DM", nationality: "France", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/383350.png" },
    ],
    recentNews: [
      { title: "Mbappé leads France charge ahead of 2026 World Cup", tag: "World Cup", date: "2025-05-20" },
      { title: "Deschamps announces squad for summer internationals", tag: "International", date: "2025-05-12" },
      { title: "France's golden generation ready to dominate World Cup in USA", tag: "Analysis", date: "2025-05-05" },
    ],
    stats: [
      { label: "FIFA Ranking", value: "#2" },
      { label: "World Cups Won", value: "2" },
      { label: "Euro Championships", value: "2" },
      { label: "World Cup Appearances", value: "16" },
    ],
  },

  10: {
    id: 10,
    name: "England",
    shortName: "England",
    logo: "https://media.api-sports.io/football/teams/10.png",
    country: "World",
    isNational: true,
    founded: 1863,
    stadium: "Wembley Stadium",
    stadiumCity: "London",
    stadiumCapacity: 90000,
    manager: "Thomas Tuchel",
    primaryColor: "#FFFFFF",
    secondaryColor: "#003DA5",
    description: "England is the birthplace of football, having founded the Football Association in 1863. The Three Lions have won the World Cup once in 1966 on home soil. Wembley Stadium — 'The Home of Football' — is the iconic venue. England reached the Euro 2024 final but fell to Spain.",
    trophies: [
      { name: "FIFA World Cup", count: 1 },
      { name: "UEFA Euro Championship", count: 0 },
    ],
    keyPlayers: [
      { name: "Jude Bellingham", position: "CM", nationality: "England", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/f/f9/25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Jude_Bellingham_-_240422_190551-2_%28cropped%29.jpg/500px-25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Jude_Bellingham_-_240422_190551-2_%28cropped%29.jpg" },
      { name: "Bukayo Saka", position: "RW", nationality: "England", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/c/cd/1_bukayo_saka_arsenal_2025_%28cropped%29.jpg/500px-1_bukayo_saka_arsenal_2025_%28cropped%29.jpg" },
      { name: "Harry Kane", position: "ST", nationality: "England", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/9/91/Harry_Kane_on_October_10%2C_2023.jpg/500px-Harry_Kane_on_October_10%2C_2023.jpg" },
    ],
    recentNews: [
      { title: "Tuchel's England begin new era with dominant friendly displays", tag: "International", date: "2025-05-19" },
      { title: "Kane, Bellingham, Saka: England's Holy Trinity target World Cup glory", tag: "World Cup", date: "2025-05-12" },
      { title: "Wembley hosts record crowd for England qualifier", tag: "International", date: "2025-05-05" },
    ],
    stats: [
      { label: "FIFA Ranking", value: "#4" },
      { label: "World Cups Won", value: "1" },
      { label: "World Cup Appearances", value: "16" },
      { label: "Wembley Capacity", value: "90,000" },
    ],
  },

  25: {
    id: 25,
    name: "Germany",
    shortName: "Germany",
    logo: "https://media.api-sports.io/football/teams/25.png",
    country: "World",
    isNational: true,
    founded: 1900,
    stadium: "Allianz Arena / Berlin Olympiastadion",
    stadiumCity: "Munich / Berlin",
    stadiumCapacity: 71000,
    manager: "Julian Nagelsmann",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    description: "Germany is one of football's giants, having won 4 FIFA World Cups (1954, 1974, 1990, 2014) and 3 UEFA European Championships. Die Mannschaft are renowned for their efficiency, organization and ability to perform on the biggest stage.",
    trophies: [
      { name: "FIFA World Cup", count: 4 },
      { name: "UEFA Euro Championship", count: 3 },
      { name: "Olympic Gold Medal", count: 1 },
    ],
    keyPlayers: [
      { name: "Jamal Musiala", position: "AM", nationality: "Germany", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/168542.png" },
      { name: "Florian Wirtz", position: "AM", nationality: "Germany", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/293012.png" },
      { name: "Kai Havertz", position: "ST", nationality: "Germany", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/41184.png" },
    ],
    recentNews: [
      { title: "Germany's young talent blossoms under Nagelsmann ahead of 2026", tag: "World Cup", date: "2025-05-18" },
      { title: "Musiala and Wirtz: the creative pair set to power Germany's revival", tag: "Analysis", date: "2025-05-11" },
      { title: "Euro 2024 hosts inspire new generation to chase World Cup glory", tag: "International", date: "2025-05-04" },
    ],
    stats: [
      { label: "FIFA Ranking", value: "#12" },
      { label: "World Cups Won", value: "4" },
      { label: "Euro Championships", value: "3" },
      { label: "World Cup Appearances", value: "20" },
    ],
  },

  27: {
    id: 27,
    name: "Portugal",
    shortName: "Portugal",
    logo: "https://media.api-sports.io/football/teams/27.png",
    country: "World",
    isNational: true,
    founded: 1914,
    stadium: "Estádio da Luz",
    stadiumCity: "Lisbon",
    stadiumCapacity: 64642,
    manager: "Roberto Martínez",
    primaryColor: "#006600",
    secondaryColor: "#FF0000",
    description: "Portugal is one of Europe's top football nations, having won the UEFA Euro 2016 and the inaugural UEFA Nations League in 2019. The Seleção have been defined by the brilliance of Cristiano Ronaldo, the all-time top scorer in international football.",
    trophies: [
      { name: "UEFA Euro Championship", count: 1 },
      { name: "UEFA Nations League", count: 1 },
    ],
    keyPlayers: [
      { name: "Cristiano Ronaldo", position: "ST", nationality: "Portugal", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/874.png" },
      { name: "Bruno Fernandes", position: "CAM", nationality: "Portugal", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/17844.png" },
      { name: "Rafael Leão", position: "LW", nationality: "Portugal", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/207282.png" },
    ],
    recentNews: [
      { title: "Portugal qualify for 2026 World Cup in style under Martínez", tag: "World Cup", date: "2025-05-20" },
      { title: "Ronaldo becomes first player to score 130 international goals", tag: "Records", date: "2025-05-12" },
      { title: "Post-Ronaldo era: Portugal's new generation step up", tag: "Analysis", date: "2025-05-05" },
    ],
    stats: [
      { label: "FIFA Ranking", value: "#6" },
      { label: "Euro Championships", value: "1" },
      { label: "Nations Leagues", value: "1" },
      { label: "World Cup Appearances", value: "9" },
    ],
  },

  66: {
    id: 66,
    name: "Aston Villa",
    shortName: "Aston Villa",
    logo: "https://media.api-sports.io/football/teams/66.png",
    country: "England",
    isNational: false,
    founded: 1874,
    stadium: "Villa Park",
    stadiumCity: "Birmingham",
    stadiumCapacity: 42682,
    manager: "Unai Emery",
    league: "Premier League",
    leagueLogo: "https://media.api-sports.io/football/leagues/39.png",
    primaryColor: "#670E36",
    secondaryColor: "#95BFE5",
    description: "Aston Villa Football Club is an English professional football club based in Aston, Birmingham. Founded in 1874, they have played at their home ground, Villa Park, since 1897.",
    trophies: [
      { name: "English Top Flight", count: 7 },
      { name: "FA Cup", count: 7 },
      { name: "EFL Cup", count: 5 },
      { name: "European Cup", count: 1 }
    ],
    keyPlayers: [
      { name: "Ollie Watkins", position: "ST", nationality: "England", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/19187.png" }
    ],
    recentNews: [],
    stats: []
  },

  34: {
    id: 34,
    name: "Newcastle United F.C.",
    shortName: "Newcastle",
    logo: "https://media.api-sports.io/football/teams/34.png",
    country: "England",
    isNational: false,
    founded: 1892,
    stadium: "St James' Park",
    stadiumCity: "Newcastle upon Tyne",
    stadiumCapacity: 52305,
    manager: "Eddie Howe",
    league: "Premier League",
    leagueLogo: "https://media.api-sports.io/football/leagues/39.png",
    primaryColor: "#241F20",
    secondaryColor: "#FFFFFF",
    description: "Newcastle United Football Club is an English professional football club based in Newcastle upon Tyne, playing in the Premier League. The club was founded in 1892 by the merger of Newcastle East End and Newcastle West End.",
    trophies: [
      { name: "English Top Flight", count: 4 },
      { name: "FA Cup", count: 6 }
    ],
    keyPlayers: [
      { name: "Alexander Isak", position: "ST", nationality: "Sweden", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/0/00/UEFA_EURO_qualifiers_Sweden_vs_Spain_20191015_Alexander_Isak_56_%28cropped%29.jpg/500px-UEFA_EURO_qualifiers_Sweden_vs_Spain_20191015_Alexander_Isak_56_%28cropped%29.jpg" }
    ],
    recentNews: [],
    stats: []
  },

  530: {
    id: 530,
    name: "Atlético Madrid",
    shortName: "Atlético",
    logo: "https://media.api-sports.io/football/teams/530.png",
    country: "Spain",
    isNational: false,
    founded: 1903,
    stadium: "Estadio Cívitas Metropolitano",
    stadiumCity: "Madrid",
    stadiumCapacity: 70460,
    manager: "Diego Simeone",
    league: "La Liga",
    leagueLogo: "https://media.api-sports.io/football/leagues/140.png",
    primaryColor: "#CB3524",
    secondaryColor: "#272E61",
    description: "Club Atlético de Madrid is a Spanish professional football club based in Madrid that plays in La Liga. They play their home games at the Cívitas Metropolitano.",
    trophies: [
      { name: "La Liga", count: 11 },
      { name: "Copa del Rey", count: 10 },
      { name: "Europa League", count: 3 }
    ],
    keyPlayers: [
      { name: "Antoine Griezmann", position: "AM", nationality: "France", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/6/6e/FRA-ARG_%2810%29_%28cropped%29.jpg/500px-FRA-ARG_%2810%29_%28cropped%29.jpg" }
    ],
    recentNews: [],
    stats: []
  },

  168: {
    id: 168,
    name: "Bayer Leverkusen",
    shortName: "Leverkusen",
    logo: "https://media.api-sports.io/football/teams/168.png",
    country: "Germany",
    isNational: false,
    founded: 1904,
    stadium: "BayArena",
    stadiumCity: "Leverkusen",
    stadiumCapacity: 30210,
    manager: "Xabi Alonso",
    league: "Bundesliga",
    leagueLogo: "https://media.api-sports.io/football/leagues/78.png",
    primaryColor: "#E32221",
    secondaryColor: "#000000",
    description: "Bayer 04 Leverkusen is a German professional football club based in Leverkusen. Under Xabi Alonso, they famously went undefeated to win the 2023-2024 Bundesliga title.",
    trophies: [
      { name: "Bundesliga", count: 1 },
      { name: "DFB-Pokal", count: 2 },
      { name: "UEFA Cup", count: 1 }
    ],
    keyPlayers: [
      { name: "Florian Wirtz", position: "AM", nationality: "Germany", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Florian_Wirtz%2C_2022-07-31%2C_Saisoner%C3%B6ffnung_Bayer_04%2C_Leverkusen_%281%29_%28cropped%29.jpg/500px-Florian_Wirtz%2C_2022-07-31%2C_Saisoner%C3%B6ffnung_Bayer_04%2C_Leverkusen_%281%29_%28cropped%29.jpg" }
    ],
    recentNews: [],
    stats: []
  },

  165: {
    id: 165,
    name: "Borussia Dortmund",
    shortName: "Dortmund",
    logo: "https://media.api-sports.io/football/teams/165.png",
    country: "Germany",
    isNational: false,
    founded: 1909,
    stadium: "Signal Iduna Park",
    stadiumCity: "Dortmund",
    stadiumCapacity: 81365,
    manager: "Nuri Şahin",
    league: "Bundesliga",
    leagueLogo: "https://media.api-sports.io/football/leagues/78.png",
    primaryColor: "#FDE100",
    secondaryColor: "#000000",
    description: "Borussia Dortmund is a German professional football club based in Dortmund. They are known for their famous 'Yellow Wall' and passionate fan base at Signal Iduna Park.",
    trophies: [
      { name: "Bundesliga", count: 8 },
      { name: "DFB-Pokal", count: 5 },
      { name: "UEFA Champions League", count: 1 }
    ],
    keyPlayers: [
      { name: "Julian Brandt", position: "AM", nationality: "Germany", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/25015.png" }
    ],
    recentNews: [],
    stats: []
  },



  9: {
    id: 9,
    name: "Spain",
    shortName: "Spain",
    logo: "https://media.api-sports.io/football/teams/9.png",
    country: "World",
    isNational: true,
    founded: 1913,
    stadium: "Estadio de La Cartuja",
    stadiumCity: "Seville",
    stadiumCapacity: 57619,
    manager: "Luis de la Fuente",
    primaryColor: "#AA151B",
    secondaryColor: "#F1BF00",
    description: "Spain is one of football's most successful nations of the 21st century, winning an unprecedented three consecutive major tournaments: Euro 2008, World Cup 2010, and Euro 2012. La Roja also won Euro 2024 in Germany, becoming the first team to win four European Championships.",
    trophies: [
      { name: "FIFA World Cup", count: 1 },
      { name: "UEFA Euro Championship", count: 4 },
      { name: "Olympic Gold Medal", count: 1 },
    ],
    keyPlayers: [
      { name: "Lamine Yamal", position: "RW", nationality: "Spain", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Lamine_Yamal_in_2025.jpg/500px-Lamine_Yamal_in_2025.jpg" },
      { name: "Pedri", position: "CM", nationality: "Spain", image: "https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/1/13/Pedri.jpg/500px-Pedri.jpg" },
      { name: "Nico Williams", position: "LW", nationality: "Spain", image: "https://images.weserv.nl/?url=media.api-sports.io/football/players/360779.png" },
    ],
    recentNews: [
      { title: "Spain look unstoppable as they target 2026 World Cup glory", tag: "World Cup", date: "2025-05-20" },
      { title: "Lamine Yamal: Spain's teenage sensation on Ballon d'Or shortlist", tag: "Awards", date: "2025-05-13" },
      { title: "Euro 2024 champions Spain unveil next wave of brilliant talent", tag: "International", date: "2025-05-06" },
    ],
    stats: [
      { label: "FIFA Ranking", value: "#3" },
      { label: "World Cups Won", value: "1" },
      { label: "Euro Championships", value: "4" },
      { label: "World Cup Appearances", value: "16" },
    ],
  },
};

// Fallback for teams not in detail map
export function getTeamDetail(id: number, fallback: { name: string; logo: string; country: string }): TeamDetail {
  if (TEAM_DETAILS[id]) return TEAM_DETAILS[id];

  const isNational = fallback.country === "World";
  return {
    id,
    name: fallback.name,
    shortName: fallback.name,
    logo: fallback.logo,
    country: fallback.country,
    isNational,
    founded: isNational ? 1900 : 1950,
    stadium: isNational ? "National Stadium" : "Home Stadium",
    stadiumCity: fallback.country,
    stadiumCapacity: 0,
    manager: "Information coming soon",
    primaryColor: "#6366f1",
    secondaryColor: "#FFFFFF",
    description: `${fallback.name} is a ${isNational ? "national football team" : "professional football club"} from ${isNational ? "the country of " + fallback.name : fallback.country}. More detailed information coming soon.`,
    trophies: [],
    keyPlayers: [],
    recentNews: [
      { title: `${fallback.name} latest news and updates`, tag: "Club News", date: new Date().toISOString().split("T")[0] },
    ],
    stats: [],
  };
}
